const COLORS = [
  'Amber',
  'Amethyst',
  'Aqua',
  'Azure',
  'Beige',
  'Black',
  'Blue',
  'Bronze',
  'Brown',
  'Burgundy',
  'Cerulean',
  'Charcoal',
  'Chartreuse',
  'Cobalt',
  'Coral',
  'Crimson',
  'Cyan',
  'Emerald',
  'Fuchsia',
  'Gold',
  'Goldenrod',
  'Gray',
  'Green',
  'Indigo',
  'Ivory',
  'Jade',
  'Lavender',
  'Lilac',
  'Lime',
  'Magenta',
  'Maroon',
  'Mint',
  'Mustard',
  'Navy',
  'Olive',
  'Orange',
  'Peach',
  'Periwinkle',
  'Pink',
  'Platinum',
  'Plum',
  'Purple',
  'Red',
  'Rose',
  'Ruby',
  'Saffron',
  'Silver',
  'Teal',
  'Turquoise',
  'Violet',
  'White',
  'Yellow',
] as const;

const ANIMALS = [
  'Albatross',
  'Alligator',
  'Antelope',
  'Armadillo',
  'Badger',
  'Barracuda',
  'Beaver',
  'Bison',
  'Bobcat',
  'Buffalo',
  'Butterfly',
  'Camel',
  'Caribou',
  'Cheetah',
  'Chameleon',
  'Cobra',
  'Cougar',
  'Coyote',
  'Crane',
  'Crocodile',
  'Dolphin',
  'Dragonfly',
  'Eagle',
  'Falcon',
  'Ferret',
  'Fox',
  'Gazelle',
  'Giraffe',
  'Gorilla',
  'Hedgehog',
  'Heron',
  'Jaguar',
  'Kangaroo',
  'Koala',
  'Leopard',
  'Lynx',
  'Manatee',
  'Mongoose',
  'Moose',
  'Narwhal',
  'Octopus',
  'Otter',
  'Panda',
  'Panther',
  'Penguin',
  'Quokka',
  'Raccoon',
  'Seal',
  'Tiger',
  'Wolf',
] as const;

type RandomCharacterNameOptions = {
  random?: () => number;
};

export function generateRandomCharacterName(options: RandomCharacterNameOptions = {}): string {
  const random = options.random ?? Math.random;

  const color = COLORS[Math.floor(random() * COLORS.length)] ?? COLORS[0];
  const animal = ANIMALS[Math.floor(random() * ANIMALS.length)] ?? ANIMALS[0];
  const number = Math.floor(random() * 10_000)
    .toString()
    .padStart(4, '0');

  return `${color} ${animal} ${number}`;
}

export type RandomCharacterNameGenerator = typeof generateRandomCharacterName;
