import { TargetLanguageCode } from './languages';

export const SCRIPT_PLACEHOLDERS: Record<TargetLanguageCode, string> = {
  en: `This is an auto‑generated sample script used during development and testing to simulate a realistic, human‑readable narration. It deliberately exceeds three hundred characters so that validation rules for minimum script length are satisfied without manual edits. In a real system, this content would be produced by the language model based on the user’s prompt, with clear pacing, scene transitions, and a concise call to action at the end. For now, please treat this as placeholder text that can be approved to move the project forward through subsequent processing steps.`,
  ru: `Это автоматически сгенерированный пример сценария для разработки и тестирования, который имитирует реалистичную, удобочитаемую озвучку. Текст намеренно длиннее трехсот символов, чтобы соблюсти правила проверки минимальной длины без ручных правок. В реальной системе содержание создается языковой моделью на основе идеи пользователя, со структурой, паузами и ясным призывом к действию. Сейчас это лишь шаблонный текст, который можно утвердить, чтобы перейти к следующим этапам обработки проекта.`,
  es: `Este es un guion de ejemplo generado automáticamente para desarrollo y pruebas, que simula una narración realista y legible. Supera deliberadamente los trescientos caracteres para cumplir con las reglas de validación sin ediciones manuales. En un sistema real, el contenido lo produciría el modelo de lenguaje según la idea del usuario, con ritmo claro, transiciones y un cierre con llamado a la acción. Por ahora, trátalo como texto de marcador que permite avanzar el proyecto a las siguientes etapas.`,
  fr: `Ceci est un script d’exemple généré automatiquement pour le développement et les tests, simulant une narration réaliste et lisible. Il dépasse volontairement trois cents caractères afin de satisfaire les contraintes de longueur minimale sans modifications manuelles. Dans un système réel, le contenu serait produit par le modèle de langue à partir de l’idée de l’utilisateur, avec un rythme clair, des transitions et un appel à l’action concis. Pour l’instant, considérez-le comme un texte de remplacement permettant d’avancer aux étapes suivantes.`,
  de: `Dies ist ein automatisch generiertes Beispielszenario für Entwicklung und Tests, das eine realistische, gut lesbare Erzählung simuliert. Es überschreitet bewusst dreihundert Zeichen, um die Mindestlängenprüfung ohne manuelle Anpassungen zu erfüllen. In einem echten System würde der Inhalt vom Sprachmodell basierend auf der Idee des Nutzers erstellt werden – mit klarem Rhythmus, Übergängen und einem prägnanten Call-to-Action. Vorerst dient dieser Text als Platzhalter, um das Projekt in die nächsten Verarbeitungsschritte zu führen.`,
  pt: `Este é um roteiro de exemplo gerado automaticamente para desenvolvimento e testes, que simula uma narração realista e legível. Ele excede deliberadamente trezentos caracteres para cumprir a validação de comprimento mínimo sem edições manuais. Em um sistema real, o conteúdo seria produzido pelo modelo de linguagem a partir da ideia do usuário, com ritmo claro, transições e um chamado à ação conciso. Por agora, trate-o como texto de placeholder para avançar o projeto às próximas etapas.`,
  it: `Questo è uno script di esempio generato automaticamente per sviluppo e test, che simula una narrazione realistica e leggibile. Supera volutamente i trecento caratteri per soddisfare i requisiti di lunghezza minima senza modifiche manuali. In un sistema reale, il contenuto sarebbe prodotto dal modello linguistico sulla base dell’idea dell’utente, con ritmo chiaro, transizioni e una concisa call to action finale. Per ora, consideralo testo segnaposto che consente di far avanzare il progetto alle fasi successive.`,
};

export function getPlaceholderForLanguage(code: TargetLanguageCode): string {
  return SCRIPT_PLACEHOLDERS[code] || SCRIPT_PLACEHOLDERS.en;
}
